export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const INIT_INGREDIENTS_FAILED = "INIT_INGREDIENTS_FAILED";

export const SUBMIT_ORDER = "SUBMIT_ORDER";
export const SUBMIT_ORDER_FAILED = "SUBMIT_ORDER_FAILED";
export const LOADING_PAGE = "LOADING_PAGE";

export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_LOADING = "FETCH_ORDERS_LOADING";
export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";
